slam_toolbox:
  ros__parameters:

    mode: localization

    map_frame: map
    odom_frame: odom
    base_frame: base_footprint

    scan_topic: /scan

    use_odometry: true
    use_scan_matching: true

    map_file_name: "/home/m-gnr/develop/ros2_ws/maps/hamals_map.yaml"

    resolution: 0.03
    max_laser_range: 8.0